### ISSUE TITLE
Getting this repeatedly (after every letter) 

### ISSUE THREAD

**Issue by tempit** [wix/stylable-intelligence#106]
TypeError: Cannot read property 'input' of undefined
    at createRange (/home/wix/projects/stylable-intelligence/packages/client/server/src/diagnosis.js:44:27)
    at reportToDiagnostic (/home/wix/projects/stylable-intelligence/packages/client/server/src/diagnosis.js:36:17)
    at Array.map (native)
    at Object.createDiagnosis (/home/wix/projects/stylable-intelligence/packages/client/server/src/diagnosis.js:30:40)
    at /home/wix/projects/stylable-intelligence/packages/client/server/src/server.js:55:35
    at CallbackList.invoke (/home/wix/projects/stylable-intelligence/packages/client/server/node_modules/vscode-jsonrpc/lib/events.js:71:39)
    at Emitter.fire (/home/wix/projects/stylable-intelligence/packages/client/server/node_modules/vscode-jsonrpc/lib/events.js:135:36)
    at connection.onDidChangeTextDocument (/home/wix/projects/stylable-intelligence/packages/client/server/node_modules/vscode-languageserver/lib/main.js:184:46)
    at handleNotification (/home/wix/projects/stylable-intelligence/packages/client/server/node_modules/vscode-jsonrpc/lib/main.js:476:43)
    at processMessageQueue (/home/wix/projects/stylable-intelligence/packages/client/server/node_modules/vscode-jsonrpc/lib/main.js:248:17)
[Trace - 11:37:57 AM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///home/wix/projects/stylable-intelligence/packages/client/test/demo/import.st.css",
        "version": 39
    },
    "contentChanges": [
        {
            "text": ".shlomo {\n    color: black;\n}\n\n.momo{\n    -st-states: anotherState,oneMoreState;\n}\n\n.root {\n    -st-states : state,otherState;\n}\n\n:vars {\n    color1: red;\n    color2: blue;\n    blue: green;\n}\n\n.grid {\n    color: lavenderblush;\n}\n\n@custom-selector :--pon\n"
        }
    ]
}

**Comment by qballer** [comment]
should be resolved in @tempit next PR
