### ISSUE TITLE
flaky e2e test: test diagnostics -> should support single file error

### ISSUE THREAD

**Issue by AviVahl** [wix/stylable-intelligence#308]
fails on Mac CI sometimes. Always with the same error:
```
  test diagnostics
    1) should support single file error

  3 passing (2s)
  1 pending
  1 failing

  1) test diagnostics
       should support single file error:
     AssertionError: Target cannot be null or undefined.
  	at assertDiagnosticExist (dist/test/e2e/diagnostics.test.js:26:46)
  	at Context.<anonymous> (dist/test/e2e/diagnostics.test.js:44:20)
```

**Comment by AviVahl** [comment]
Appears to stable atm.
